version: '2'
services:
  participa:
    image: bec/participa:1.0.0
    build:
      context: .
      dockerfile: config/docker/Dockerfile
      args:
        - APP_HOME=/srv/www/participa
    volumes:
      - .:/srv/www/participa
    environment:
      - RAILS_ENV=development
    ports:
      - "4000:3000"
    depends_on:
      - postgres
      - redis
      - mailcatcher
    command: bundle exec rails server -p 3000 -b '0.0.0.0'

  postgres:
    image: postgres:9.6

  redis:
    image: redis:2.8

  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - "4080:1080"
